Add plugin scaffold
efdevcon/pretix-attestation-placeholder-plugin pull request #8
Opened 2021-01-14 19:37 UTC by Nurts

### What was wrong ?

- #3 

### How it was fixed ?

- Added placeholder plugin as described here: https://docs.pretix.eu/en/latest/development/api/placeholder.html#placeholder-registration

### To Do

- [ ] Maybe replace with some static text (instead of the link) for the scaffold.

2021-01-14 19:44 UTC, Nurts commented
Hi @ligi , I am not sure which link you mentioned that should be replaced in #3

2021-01-16 21:39 UTC, ligi commented
the main purpose of this plugin to replace a placeholder with a link generated by the alphawallet tool - this is the link I refer to in the issue

2021-01-16 21:42 UTC, ligi requested changes

2021-01-16 21:42 UTC, ligi commented on setup.py
> +    author_email='Your email',
```suggestion
    author_email='ticketing@devcon.org',
```

2021-01-16 21:42 UTC, ligi commented on setup.py
> +        "pretix>=3.8.0",
in pretix_attestation_plugin/__init__.py we require >=3.7.0 - maybe we should do the same there or here. Let's just unify it - both fine with me

2021-01-19 01:04 UTC, ligi approved these changes

2021-01-19 01:04 UTC, merged